error checks added

diff --git a/gds2svg b/gds2svg
--- a/gds2svg
+++ b/gds2svg
@@ -13,6 +13,7 @@ if [ "$#" -lt "1" ]; then
 fi
 
 gdsfile=$1
+techfile=$2
 filename=$(basename "$gdsfile")
 filename="${filename%.*}"
 
@@ -25,10 +26,11 @@ svgfile=${filename}.svg
 # echo $svgfile
 
 # Convert GDS 2 ASCII Dump
+command -v gds2ascii >/dev/null 2>&1 || { echo >&2 "Executable 'gds2ascii' is not in the PATH.  Aborting."; exit 1; }
 gds2ascii $gdsfile > $asciidumpfile
 
 # Convert ASCII Dump to SVG 
-asciidump2svg $asciidumpfile $svgfile
+$(dirname $0)/asciidump2svg -i $asciidumpfile -o $svgfile -t $techfile
 
 # Fit the design canvas
 inkscape --verb=FitCanvasToDrawing --verb=ZoomPage --verb=FileSave --verb=FileQuit $svgfile 2> /dev/null
